steps:
  # Paso 1: Clonar el repositorio de GitHub utilizando el token desde Secret Manager
  #sarralao
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Clone GitHub repository
    entrypoint: bash
    args:
      - '-c'
      - |
        git clone https://$$GH_TOKEN@github.com/amoreno-gene/orchestration.git
        cd orchestration
    secretEnv: ['GH_TOKEN']

  # Paso 2: Sincronizar los DAGs con el bucket de Composer
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', 'dags/', 'gs://europe-west4-composer-dev-20d58bfa-bucket/dags/']

# Definir secretos disponibles desde Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/extracciones-426907/secrets/GITHUB_TOKEN/versions/latest
    env: GH_TOKEN  # Aquí se establece GH_TOKEN como variable de entorno

options:
  logging: CLOUD_LOGGING_ONLY
