steps:
  # Paso 1: Crear una pull request en GitHub utilizando el token desde Secret Manager
  - name: 'launcher.gcr.io/google/ubuntu1604'
    id: Create GitHub pull request
    entrypoint: bash
    args:
      - -c
      - |
        curl -X POST -H "Authorization: Bearer $GH_TOKEN" -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/amoreno-gene/orchestration/pulls -d '{"head":"HEAD_BRANCH","base":"BASE_BRANCH", "title":"NEW_PR"}'
    secretEnv: ['GH_TOKEN']  # La variable de entorno se define aquí

# Definir secretos disponibles desde Secret Manager
availableSecrets:
  secretManager:
  - versionName: projects/extracciones-426907/secrets/GITHUB_TOKEN/versions/latest
    env: GH_TOKEN  # Aquí se establece GH_TOKEN como variable de entorno

options:
  logging: CLOUD_LOGGING_ONLY
