steps:
  # Paso 1: Obtener el token de GitHub desde Secret Manager y clonar el repositorio
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://$(gcloud secrets versions access latest --secret="GITHUB_TOKEN")@github.com/amoreno-gene/orchestration.git
        cd orchestration

  # Paso 2: Sincronizar los DAGs con el bucket de Composer
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['rsync', '-r', 'dags/', 'gs://europe-west4-composer-dev-20d58bfa-bucket/dags/']

options:
  logging: CLOUD_LOGGING_ONLY
